(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var n;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var p="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var r=ba(this);function u(a,b){if(b)a:{var c=r;a=a.split(".");for(var d=0;d<a.length-1;d++){var f=a[d];if(!(f in c))break a;c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&p(c,a,{configurable:!0,writable:!0,value:b})}}
u("Symbol",function(a){function b(g){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(g||"")+"_"+f++,g)}function c(g,e){this.g=g;p(this,"description",{configurable:!0,writable:!0,value:e})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",f=0;return b});
u("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=r[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&p(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ca(aa(this))}})}return a});function ca(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function da(a){return a.raw=a}function v(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var ea="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},fa;
if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
function w(a,b){a.prototype=ea(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.X=b.prototype}function la(){this.l=!1;this.g=null;this.o=void 0;this.h=1;this.A=0;this.j=null}function ma(a){if(a.l)throw new TypeError("Generator is already running");a.l=!0}la.prototype.u=function(a){this.o=a};function na(a,b){a.j={ha:b,ia:!0};a.h=a.A}
la.prototype.return=function(a){this.j={return:a};this.h=this.A};function oa(a){this.g=new la;this.h=a}function pa(a,b){ma(a.g);var c=a.g.g;if(c)return qa(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return y(a)}
function qa(a,b,c,d){try{var f=b.call(a.g.g,c);if(!(f instanceof Object))throw new TypeError("Iterator result "+f+" is not an object");if(!f.done)return a.g.l=!1,f;var g=f.value}catch(e){return a.g.g=null,na(a.g,e),y(a)}a.g.g=null;d.call(a.g,g);return y(a)}function y(a){for(;a.g.h;)try{var b=a.h(a.g);if(b)return a.g.l=!1,{value:b.value,done:!1}}catch(c){a.g.o=void 0,na(a.g,c)}a.g.l=!1;if(a.g.j){b=a.g.j;a.g.j=null;if(b.ia)throw b.ha;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function ra(a){this.next=function(b){ma(a.g);a.g.g?b=qa(a,a.g.g.next,b,a.g.u):(a.g.u(b),b=y(a));return b};this.throw=function(b){ma(a.g);a.g.g?b=qa(a,a.g.g["throw"],b,a.g.u):(na(a.g,b),b=y(a));return b};this.return=function(b){return pa(a,b)};this[Symbol.iterator]=function(){return this}}function ta(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,f){function g(e){e.done?d(e.value):Promise.resolve(e.value).then(b,c).then(g,f)}g(a.next())})}
function ua(a){return ta(new ra(new oa(a)))}function va(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
u("Promise",function(a){function b(e){this.g=0;this.j=void 0;this.h=[];this.A=!1;var h=this.l();try{e(h.resolve,h.reject)}catch(k){h.reject(k)}}function c(){this.g=null}function d(e){return e instanceof b?e:new b(function(h){h(e)})}if(a)return a;c.prototype.h=function(e){if(null==this.g){this.g=[];var h=this;this.j(function(){h.o()})}this.g.push(e)};var f=r.setTimeout;c.prototype.j=function(e){f(e,0)};c.prototype.o=function(){for(;this.g&&this.g.length;){var e=this.g;this.g=[];for(var h=0;h<e.length;++h){var k=
e[h];e[h]=null;try{k()}catch(l){this.l(l)}}}this.g=null};c.prototype.l=function(e){this.j(function(){throw e;})};b.prototype.l=function(){function e(l){return function(m){k||(k=!0,l.call(h,m))}}var h=this,k=!1;return{resolve:e(this.J),reject:e(this.o)}};b.prototype.J=function(e){if(e===this)this.o(new TypeError("A Promise cannot resolve to itself"));else if(e instanceof b)this.L(e);else{a:switch(typeof e){case "object":var h=null!=e;break a;case "function":h=!0;break a;default:h=!1}h?this.G(e):this.u(e)}};
b.prototype.G=function(e){var h=void 0;try{h=e.then}catch(k){this.o(k);return}"function"==typeof h?this.M(h,e):this.u(e)};b.prototype.o=function(e){this.F(2,e)};b.prototype.u=function(e){this.F(1,e)};b.prototype.F=function(e,h){if(0!=this.g)throw Error("Cannot settle("+e+", "+h+"): Promise already settled in state"+this.g);this.g=e;this.j=h;2===this.g&&this.K();this.H()};b.prototype.K=function(){var e=this;f(function(){if(e.I()){var h=r.console;"undefined"!==typeof h&&h.error(e.j)}},1)};b.prototype.I=
function(){if(this.A)return!1;var e=r.CustomEvent,h=r.Event,k=r.dispatchEvent;if("undefined"===typeof k)return!0;"function"===typeof e?e=new e("unhandledrejection",{cancelable:!0}):"function"===typeof h?e=new h("unhandledrejection",{cancelable:!0}):(e=r.document.createEvent("CustomEvent"),e.initCustomEvent("unhandledrejection",!1,!0,e));e.promise=this;e.reason=this.j;return k(e)};b.prototype.H=function(){if(null!=this.h){for(var e=0;e<this.h.length;++e)g.h(this.h[e]);this.h=null}};var g=new c;b.prototype.L=
function(e){var h=this.l();e.P(h.resolve,h.reject)};b.prototype.M=function(e,h){var k=this.l();try{e.call(h,k.resolve,k.reject)}catch(l){k.reject(l)}};b.prototype.then=function(e,h){function k(t,x){return"function"==typeof t?function(P){try{l(t(P))}catch(sa){m(sa)}}:x}var l,m,q=new b(function(t,x){l=t;m=x});this.P(k(e,l),k(h,m));return q};b.prototype.catch=function(e){return this.then(void 0,e)};b.prototype.P=function(e,h){function k(){switch(l.g){case 1:e(l.j);break;case 2:h(l.j);break;default:throw Error("Unexpected state: "+
l.g);}}var l=this;null==this.h?g.h(k):this.h.push(k);this.A=!0};b.resolve=d;b.reject=function(e){return new b(function(h,k){k(e)})};b.race=function(e){return new b(function(h,k){for(var l=v(e),m=l.next();!m.done;m=l.next())d(m.value).P(h,k)})};b.all=function(e){var h=v(e),k=h.next();return k.done?d([]):new b(function(l,m){function q(P){return function(sa){t[P]=sa;x--;0==x&&l(t)}}var t=[],x=0;do t.push(void 0),x++,d(k.value).P(q(t.length-1),m),k=h.next();while(!k.done)})};return b});
u("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var f=d.length,g=0;g<f;g++){var e=d[g];if(b.call(c,e,g,d)){b=e;break a}}b=void 0}return b}});function z(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
u("WeakMap",function(a){function b(k){this.g=(h+=Math.random()+1).toString();if(k){k=v(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(k){var l=typeof k;return"object"===l&&null!==k||"function"===l}function f(k){if(!z(k,e)){var l=new c;p(k,e,{value:l})}}function g(k){var l=Object[k];l&&(Object[k]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&f(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),
m=new a([[k,2],[l,3]]);if(2!=m.get(k)||3!=m.get(l))return!1;m.delete(k);m.set(l,4);return!m.has(k)&&4==m.get(l)}catch(q){return!1}}())return a;var e="$jscomp_hidden_"+Math.random();g("freeze");g("preventExtensions");g("seal");var h=0;b.prototype.set=function(k,l){if(!d(k))throw Error("Invalid WeakMap key");f(k);if(!z(k,e))throw Error("WeakMap key fail: "+k);k[e][this.g]=l;return this};b.prototype.get=function(k){return d(k)&&z(k,e)?k[e][this.g]:void 0};b.prototype.has=function(k){return d(k)&&z(k,
e)&&z(k[e],this.g)};b.prototype.delete=function(k){return d(k)&&z(k,e)&&z(k[e],this.g)?delete k[e][this.g]:!1};return b});
u("Map",function(a){function b(){var h={};return h.B=h.next=h.head=h}function c(h,k){var l=h.g;return ca(function(){if(l){for(;l.head!=h.g;)l=l.B;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})}function d(h,k){var l=k&&typeof k;"object"==l||"function"==l?g.has(k)?l=g.get(k):(l=""+ ++e,g.set(k,l)):l="p_"+k;var m=h.h[l];if(m&&z(h.h,l))for(h=0;h<m.length;h++){var q=m[h];if(k!==k&&q.key!==q.key||k===q.key)return{id:l,list:m,index:h,s:q}}return{id:l,list:m,
index:-1,s:void 0}}function f(h){this.h={};this.g=b();this.size=0;if(h){h=v(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var h=Object.seal({x:4}),k=new a(v([[h,"s"]]));if("s"!=k.get(h)||1!=k.size||k.get({x:4})||k.set({x:4},"t")!=k||2!=k.size)return!1;var l=k.entries(),m=l.next();if(m.done||m.value[0]!=h||"s"!=m.value[1])return!1;m=l.next();return m.done||4!=m.value[0].x||
"t"!=m.value[1]||!l.next().done?!1:!0}catch(q){return!1}}())return a;var g=new WeakMap;f.prototype.set=function(h,k){h=0===h?0:h;var l=d(this,h);l.list||(l.list=this.h[l.id]=[]);l.s?l.s.value=k:(l.s={next:this.g,B:this.g.B,head:this.g,key:h,value:k},l.list.push(l.s),this.g.B.next=l.s,this.g.B=l.s,this.size++);return this};f.prototype.delete=function(h){h=d(this,h);return h.s&&h.list?(h.list.splice(h.index,1),h.list.length||delete this.h[h.id],h.s.B.next=h.s.next,h.s.next.B=h.s.B,h.s.head=null,this.size--,
!0):!1};f.prototype.clear=function(){this.h={};this.g=this.g.B=b();this.size=0};f.prototype.has=function(h){return!!d(this,h).s};f.prototype.get=function(h){return(h=d(this,h).s)&&h.value};f.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};f.prototype.keys=function(){return c(this,function(h){return h.key})};f.prototype.values=function(){return c(this,function(h){return h.value})};f.prototype.forEach=function(h,k){for(var l=this.entries(),m;!(m=l.next()).done;)m=m.value,
h.call(k,m[1],m[0],this)};f.prototype[Symbol.iterator]=f.prototype.entries;var e=0;return f});function wa(a,b){a instanceof String&&(a+="");var c=0,d=!1,f={next:function(){if(!d&&c<a.length){var g=c++;return{value:b(g,a[g]),done:!1}}d=!0;return{done:!0,value:void 0}}};f[Symbol.iterator]=function(){return f};return f}u("Array.prototype.entries",function(a){return a?a:function(){return wa(this,function(b,c){return[b,c]})}});
u("Number.isNaN",function(a){return a?a:function(b){return"number"===typeof b&&isNaN(b)}});u("Array.prototype.keys",function(a){return a?a:function(){return wa(this,function(b){return b})}});
u("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(h){return h};var f=[],g="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof g){b=g.call(b);for(var e=0;!(g=b.next()).done;)f.push(c.call(d,g.value,e++))}else for(g=b.length,e=0;e<g;e++)f.push(c.call(d,b[e],e));return f}});u("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)z(b,d)&&c.push([d,b[d]]);return c}});
u("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});u("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var f=d.length;c=c||0;for(0>c&&(c=Math.max(c+f,0));c<f;c++){var g=d[c];if(g===b||Object.is(g,b))return!0}return!1}});
u("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==(this+"").indexOf(b,c||0)}});
u("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});var xa=xa||{},A=this||self;function ya(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}
function za(a,b,c){return a.call.apply(a.bind,arguments)}function Aa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var f=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(f,d);return a.apply(b,f)}}return function(){return a.apply(b,arguments)}}function B(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?B=za:B=Aa;return B.apply(null,arguments)}
function Ba(a,b){function c(){}c.prototype=b.prototype;a.X=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ka=function(d,f,g){for(var e=Array(arguments.length-2),h=2;h<arguments.length;h++)e[h-2]=arguments[h];return b.prototype[f].apply(d,e)}}function Ca(a){return a};var Da={};var Ea;var Fa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};function Ga(a,b){return a<b?-1:a>b?1:0};function C(){var a=A.navigator;return a&&(a=a.userAgent)?a:""}function D(a){return-1!=C().indexOf(a)};var Ha=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ia=Array.prototype.every?function(a,b){return Array.prototype.every.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,f=0;f<c;f++)if(f in d&&!b.call(void 0,d[f],f,a))return!1;return!0};
function Ja(a,b){b=Ha(a,b);var c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c};function Ka(a){var b=La;return Object.prototype.hasOwnProperty.call(b,9)?b[9]:b[9]=a(9)};var Ma=D("Opera"),Na=D("Trident")||D("MSIE"),Oa=D("Edge"),Pa=D("Gecko")&&!(-1!=C().toLowerCase().indexOf("webkit")&&!D("Edge"))&&!(D("Trident")||D("MSIE"))&&!D("Edge"),Qa=-1!=C().toLowerCase().indexOf("webkit")&&!D("Edge"),Ra=Qa&&D("Mobile"),Sa;
a:{var Ta="",Ua=function(){var a=C();if(Pa)return/rv:([^\);]+)(\)|;)/.exec(a);if(Oa)return/Edge\/([\d\.]+)/.exec(a);if(Na)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Qa)return/WebKit\/(\S+)/.exec(a);if(Ma)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Ua&&(Ta=Ua?Ua[1]:"");if(Na){var E,Va=A.document;E=Va?Va.documentMode:void 0;if(null!=E&&E>parseFloat(Ta)){Sa=String(E);break a}}Sa=Ta}var Wa=Sa,La={};
function Xa(){return Ka(function(){for(var a=0,b=Fa(String(Wa)).split("."),c=Fa("9").split("."),d=Math.max(b.length,c.length),f=0;0==a&&f<d;f++){var g=b[f]||"",e=c[f]||"";do{g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];e=/(\d*)(\D*)(.*)/.exec(e)||["","","",""];if(0==g[0].length&&0==e[0].length)break;a=Ga(0==g[1].length?0:parseInt(g[1],10),0==e[1].length?0:parseInt(e[1],10))||Ga(0==g[2].length,0==e[2].length)||Ga(g[2],e[2]);g=g[3];e=e[3]}while(0==a)}return 0<=a})};var Ya={},F=null;
function Za(a){var b;void 0===b&&(b=0);if(!F){F={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],f=0;5>f;f++){var g=c.concat(d[f].split(""));Ya[f]=g;for(var e=0;e<g.length;e++){var h=g[e];void 0===F[h]&&(F[h]=e)}}}b=Ya[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(f=g=0;g<a.length-2;g+=3){var k=a[g],l=a[g+1];h=a[g+2];e=b[k>>2];k=b[(k&3)<<4|l>>4];l=b[(l&15)<<2|h>>6];h=b[h&63];c[f++]=""+e+k+l+h}e=0;h=d;switch(a.length-g){case 2:e=
a[g+1],h=b[(e&15)<<2]||d;case 1:a=a[g],c[f]=""+b[a>>2]+b[(a&3)<<4|e>>4]+h+d}return c.join("")};var $a="undefined"!==typeof Uint8Array,ab={};var bb;function cb(a){if(ab!==ab)throw Error("illegal external caller");this.ea=a;if(null!=a&&0===a.length)throw Error("ByteString should be constructed with non-empty values");};var G="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol(void 0):void 0;function H(a,b){Object.isFrozen(a)||(G?a[G]|=b:void 0!==a.v?a.v|=b:Object.defineProperties(a,{v:{value:b,configurable:!0,writable:!0,enumerable:!1}}))}function db(a,b){Object.isExtensible(a)&&(G?a[G]&&(a[G]&=~b):void 0!==a.v&&(a.v&=~b))}function I(a){var b;G?b=a[G]:b=a.v;return null==b?0:b}
function eb(a,b){G?a[G]=b:void 0!==a.v?a.v=b:Object.defineProperties(a,{v:{value:b,configurable:!0,writable:!0,enumerable:!1}})}function J(a){H(a,1);return a}function fb(a){H(a,17);return a}function K(a){return a?!!(I(a)&2):!1}function gb(a){if(!Array.isArray(a))throw Error("cannot mark non-array as shared mutably");db(a,16)};var hb={};function L(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}var ib=Object.freeze(J([]));function jb(a){if(K(a.i))throw Error("Cannot mutate an immutable Message");}var kb="undefined"!=typeof Symbol&&"undefined"!=typeof Symbol.hasInstance;function lb(a){return{value:a,configurable:!1,writable:!1,enumerable:!1}};function mb(a){return a.displayName||a.name||"unknown type name"}function nb(a,b){if(!(a instanceof b))throw Error("Expected instanceof "+mb(b)+" but got "+(a&&mb(a.constructor)));return a};function ob(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(a&&!Array.isArray(a)){if($a&&null!=a&&a instanceof Uint8Array)return Za(a);if(a instanceof cb){var b=a.ea;return null==b?"":"string"===typeof b?b:a.ea=Za(b)}}}return a};function pb(a,b,c){if(null!=a){if(Array.isArray(a))a=qb(a,b,c);else if(L(a)){var d={},f;for(f in a)d[f]=pb(a[f],b,c);a=d}else a=b(a);return a}}function qb(a,b,c){var d=Array.prototype.slice.call(a);c(a,d);for(a=0;a<d.length;a++)d[a]=pb(d[a],b,c);return d}function rb(a){if(a.ba===hb)return a.toJSON();a=ob(a);return Array.isArray(a)?qb(a,rb,sb):a}function sb(){};function tb(a,b,c){return-1===b?null:b>=a.D?a.m?a.m[b]:void 0:(void 0===c?0:c)&&a.m&&(c=a.m[b],null!=c)?c:a.i[b+a.C]}function M(a,b,c,d,f){d=void 0===d?!1:d;(void 0===f?0:f)||jb(a);a.Z&&(a.Z=void 0);if(b>=a.D||d)return(a.m||(a.m=a.i[a.D+a.C]={}))[b]=c,a;void 0!==a.m&&a.D>=a.i.length?(d=a.i.length-1,f=b+a.C,f>=d?(a.i[d]=void 0,a.i[f]=c,a.i.push(a.m)):a.i[f]=c):a.i[b+a.C]=c;void 0!==a.m&&b in a.m&&delete a.m[b];return a}function N(a,b){jb(a);M(a,b,void 0,!1);return a}
function O(a,b){a=tb(a,b);a=null==a?a:!!a;return null==a?!1:a};function ub(a,b,c,d,f,g){if(a=a.g&&a.g[c]){d=g.V?J(a.slice()):a;a=0<d.length?d[0].constructor:void 0;jb(b);if(null!=d){f=J([]);g=!1;for(var e=0;e<d.length;e++)f[e]=nb(d[e],a).i,g=g||K(f[e]);b.g||(b.g={});b.g[c]=d;d=f;g?db(d,8):H(d,8)}else b.g&&(b.g[c]=void 0),f=ib;M(b,c,f)}else $a&&d instanceof Uint8Array?f=d.length?new cb(new Uint8Array(d)):bb||(bb=new cb(null)):(Array.isArray(d)&&(f?H(d,2):d&&I(d)&1&&g.V?(f=Array.prototype.slice.call(d),eb(f,(I(d)|0)&-51),d=f):gb(d)),f=d),M(b,c,f)};function Q(a,b,c){a||(a=vb);vb=null;var d=this.constructor.g||0,f=0<d,g=this.constructor.h,e=!1;if(!a){var h=g?[g]:[];H(h,48);a=h;h=!0}else if(h=!!(I(a)&16))e=I(a),eb(a,e|32),e=!!(e&32);f&&0<a.length&&L(a[a.length-1])&&"g"in a[a.length-1]&&(d=0);this.C=(g?0:-1)-d;this.g=void 0;this.i=a;a:{g=this.i.length;d=g-1;if(g&&(g=this.i[d],L(g))){this.m=g;b=Object.keys(g);0<b.length&&Ia(b,isNaN)?this.D=Number.MAX_VALUE:this.D=d-this.C;break a}void 0!==b&&-1<b?(this.D=Math.max(b,d+1-this.C),this.m=void 0):this.D=
Number.MAX_VALUE}if(!f&&this.m&&"g"in this.m)throw Error('Unexpected "g" flag in sparse object of message that is not a group type.');if(c)for(f=h&&!e?fb:J,b=0;b<c.length;b++)h=c[b],(e=tb(this,h))?Array.isArray(e)&&f(e):M(this,h,ib,!1,!0)}Q.prototype.toJSON=function(){return qb(this.i,rb,sb)};
Q.prototype.O=function(){if(K(this.i)){var a={V:!0};var b=K(this.i);if(b&&!a.V)throw Error("copyRepeatedFields must be true for frozen messages");b||gb(this.i);var c=new this.constructor;this.aa&&(c.aa=this.aa.slice());for(var d=this.i,f=0;f<d.length;f++){var g=d[f];if(f===d.length-1&&L(g))for(var e in g){var h=+e;Number.isNaN(h)?(c.m||(c.m=c.i[c.D+c.C]={}))[e]=g[e]:ub(this,c,h,g[e],b,a)}else ub(this,c,f-this.C,g,b,a)}c.Z=this;a=c}else a=this;return a};Q.prototype.ba=hb;Q.prototype.toString=function(){return this.i.toString()};
var vb;function R(){Q.apply(this,arguments)}w(R,Q);R.prototype.O=function(a){return Q.prototype.O.call(this,a)};if(kb){var wb={};Object.defineProperties(R,(wb[Symbol.hasInstance]=lb(function(){throw Error(void 0);}),wb))};function S(){R.apply(this,arguments)}w(S,R);S.prototype.O=function(a){return R.prototype.O.call(this,a)};if(kb){var xb={};Object.defineProperties(S,(xb[Symbol.hasInstance]=lb(Object[Symbol.hasInstance]),xb))};/*

 SPDX-License-Identifier: Apache-2.0
*/
var yb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function zb(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var g=0;g<yb.length;g++)c=yb[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var Ab;function Bb(a,b){this.g=b===Cb?a:""}Bb.prototype.toString=function(){return this.g+""};function Db(a){return a instanceof Bb&&a.constructor===Bb?a.g:"type_error:TrustedResourceUrl"}var Cb={};function Eb(a){if(void 0===Ab){var b=null;var c=A.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("uf-api#html",{createHTML:Ca,createScript:Ca,createScriptURL:Ca})}catch(d){A.console&&A.console.error(d.message)}Ab=b}else Ab=b}a=(b=Ab)?b.createScriptURL(a):a;return new Bb(a,Cb)};function Fb(a){var b,c,d=null==(c=(b=(a.ownerDocument&&a.ownerDocument.defaultView||window).document).querySelector)?void 0:c.call(b,"script[nonce]");(b=d?d.nonce||d.getAttribute("nonce")||"":"")&&a.setAttribute("nonce",b)};function Gb(a){var b=va.apply(1,arguments);if(0===b.length)return Eb(a[0]);for(var c=[a[0]],d=0;d<b.length;d++)c.push(encodeURIComponent(b[d])),c.push(a[d+1]);return Eb(c.join(""))};try{(new self.OffscreenCanvas(0,0)).getContext("2d")}catch(a){};var Hb=/^[\w+/_-]+[=]{0,2}$/;function Ib(a){a=(a||A).document;return a.querySelector?(a=a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&Hb.test(a)?a:"":""};function Jb(a){this.g=a||A.document||document};function T(){this.o=this.o;this.A=this.A}T.prototype.o=!1;T.prototype.isDisposed=function(){return this.o};T.prototype.N=function(){if(this.A)for(;this.A.length;)this.A.shift()()};function Kb(a,b){this.type=a;this.g=this.target=b;this.defaultPrevented=!1};var Lb="closure_listenable_"+(1E6*Math.random()|0);var Mb=0;function Nb(a,b,c,d,f){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.W=f;this.key=++Mb;this.R=this.U=!1}function Ob(a){a.R=!0;a.listener=null;a.proxy=null;a.src=null;a.W=null};function Pb(a){this.src=a;this.g={};this.h=0}Pb.prototype.add=function(a,b,c,d,f){var g=a.toString();a=this.g[g];a||(a=this.g[g]=[],this.h++);var e=Qb(a,b,d,f);-1<e?(b=a[e],c||(b.U=!1)):(b=new Nb(b,this.src,g,!!d,f),b.U=c,a.push(b));return b};function Rb(a,b){var c=b.type;c in a.g&&Ja(a.g[c],b)&&(Ob(b),0==a.g[c].length&&(delete a.g[c],a.h--))}function Qb(a,b,c,d){for(var f=0;f<a.length;++f){var g=a[f];if(!g.R&&g.listener==b&&g.capture==!!c&&g.W==d)return f}return-1};var Sb="closure_lm_"+(1E6*Math.random()|0),Tb={},Ub=0;
function Vb(a,b,c,d,f){if(Array.isArray(b))for(var g=0;g<b.length;g++)Vb(a,b[g],c,d,f);else(d=ya(d)?!!d.capture:!!d,c=Wb(c),a&&a[Lb])?(a=a.j,b=String(b).toString(),b in a.g&&(g=a.g[b],c=Qb(g,c,d,f),-1<c&&(Ob(g[c]),Array.prototype.splice.call(g,c,1),0==g.length&&(delete a.g[b],a.h--)))):a&&(a=Xb(a))&&(b=a.g[b.toString()],a=-1,b&&(a=Qb(b,c,d,f)),(c=-1<a?b[a]:null)&&"number"!==typeof c&&c&&!c.R&&((f=c.src)&&f[Lb]?Rb(f.j,c):(d=c.type,b=c.proxy,f.removeEventListener?f.removeEventListener(d,b,c.capture):
f.detachEvent?f.detachEvent(d in Tb?Tb[d]:Tb[d]="on"+d,b):f.addListener&&f.removeListener&&f.removeListener(b),Ub--,(d=Xb(f))?(Rb(d,c),0==d.h&&(d.src=null,f[Sb]=null)):Ob(c))))}function Xb(a){a=a[Sb];return a instanceof Pb?a:null}var Yb="__closure_events_fn_"+(1E9*Math.random()>>>0);function Wb(a){if("function"===typeof a)return a;a[Yb]||(a[Yb]=function(b){return a.handleEvent(b)});return a[Yb]};function U(){T.call(this);this.j=new Pb(this);this.fa=this;this.M=null}Ba(U,T);U.prototype[Lb]=!0;U.prototype.removeEventListener=function(a,b,c,d){Vb(this,a,b,c,d)};
function V(a,b){var c=a.M;if(c){var d=[];for(var f=1;c;c=c.M)d.push(c),++f}a=a.fa;c=b.type||b;"string"===typeof b?b=new Kb(b,a):b instanceof Kb?b.target=b.target||a:(f=b,b=new Kb(c,a),zb(b,f));f=!0;if(d)for(var g=d.length-1;0<=g;g--){var e=b.g=d[g];f=Zb(e,c,!0,b)&&f}e=b.g=a;f=Zb(e,c,!0,b)&&f;f=Zb(e,c,!1,b)&&f;if(d)for(g=0;g<d.length;g++)e=b.g=d[g],f=Zb(e,c,!1,b)&&f}
U.prototype.N=function(){U.X.N.call(this);if(this.j){var a=this.j,b=0,c;for(c in a.g){for(var d=a.g[c],f=0;f<d.length;f++)++b,Ob(d[f]);delete a.g[c];a.h--}}this.M=null};function Zb(a,b,c,d){b=a.j.g[String(b)];if(!b)return!0;b=b.concat();for(var f=!0,g=0;g<b.length;++g){var e=b[g];if(e&&!e.R&&e.capture==c){var h=e.listener,k=e.W||e.src;e.U&&Rb(a.j,e);f=!1!==h.call(k,d)&&f}}return f&&!d.defaultPrevented};function $b(a){try{return A.JSON.parse(a)}catch(b){}a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};function ac(){}ac.prototype.g=null;function bc(a){var b;(b=a.g)||(b={},cc(a)&&(b[0]=!0,b[1]=!0),b=a.g=b);return b};var dc;function ec(){}Ba(ec,ac);function fc(a){return(a=cc(a))?new ActiveXObject(a):new XMLHttpRequest}function cc(a){if(!a.h&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.h=d}catch(f){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.h}dc=new ec;function gc(a,b,c){if("function"===typeof a)c&&(a=B(a,c));else if(a&&"function"==typeof a.handleEvent)a=B(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:A.setTimeout(a,b||0)};var hc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function ic(a){U.call(this);this.headers=new Map;this.G=a||null;this.h=!1;this.I=this.g=null;this.L="";this.l=this.K=this.u=this.J=!1;this.H=0;this.F=null;this.Y="";this.S=this.T=!1}Ba(ic,U);var jc=/^https?$/i,kc=["POST","PUT"],lc=[];function mc(a,b){var c=new ic;lc.push(c);b&&c.j.add("complete",b,!1,void 0,void 0);c.j.add("ready",c.ga,!0,void 0,void 0);c.H=2E3;c.T=!0;nc(c,a)}n=ic.prototype;n.ga=function(){this.o||(this.o=!0,this.N());Ja(lc,this)};
function nc(a,b){var c={};if(a.g)throw Error("[goog.net.XhrIo] Object is active with another request="+a.L+"; newUri="+b);a.L=b;a.J=!1;a.h=!0;a.g=a.G?fc(a.G):fc(dc);a.I=a.G?bc(a.G):bc(dc);a.g.onreadystatechange=B(a.ca,a);try{a.K=!0,a.g.open("GET",String(b),!0),a.K=!1}catch(g){oc(a);return}b=new Map(a.headers);if(c)if(Object.getPrototypeOf(c)===Object.prototype)for(var d in c)b.set(d,c[d]);else if("function"===typeof c.keys&&"function"===typeof c.get){d=v(c.keys());for(var f=d.next();!f.done;f=d.next())f=
f.value,b.set(f,c.get(f))}else throw Error("Unknown input type for opt_headers: "+String(c));c=Array.from(b.keys()).find(function(g){return"content-type"==g.toLowerCase()});d=A.FormData&&!1;!(0<=Ha(kc,"GET"))||c||d||b.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");b=v(b);for(c=b.next();!c.done;c=b.next())d=v(c.value),c=d.next().value,d=d.next().value,a.g.setRequestHeader(c,d);a.Y&&(a.g.responseType=a.Y);"withCredentials"in a.g&&a.g.withCredentials!==a.T&&(a.g.withCredentials=
a.T);try{pc(a),0<a.H&&(a.S=qc(a.g),a.S?(a.g.timeout=a.H,a.g.ontimeout=B(a.da,a)):a.F=gc(a.da,a.H,a)),a.u=!0,a.g.send(""),a.u=!1}catch(g){oc(a)}}function qc(a){return Na&&Xa()&&"number"===typeof a.timeout&&void 0!==a.ontimeout}n.da=function(){"undefined"!=typeof xa&&this.g&&(V(this,"timeout"),this.abort(8))};function oc(a){a.h=!1;a.g&&(a.l=!0,a.g.abort(),a.l=!1);rc(a);sc(a)}function rc(a){a.J||(a.J=!0,V(a,"complete"),V(a,"error"))}
n.abort=function(){this.g&&this.h&&(this.h=!1,this.l=!0,this.g.abort(),this.l=!1,V(this,"complete"),V(this,"abort"),sc(this))};n.N=function(){this.g&&(this.h&&(this.h=!1,this.l=!0,this.g.abort(),this.l=!1),sc(this,!0));ic.X.N.call(this)};n.ca=function(){this.isDisposed()||(this.K||this.u||this.l?tc(this):this.ja())};n.ja=function(){tc(this)};
function tc(a){if(a.h&&"undefined"!=typeof xa&&(!a.I[1]||4!=(a.g?a.g.readyState:0)||2!=uc(a)))if(a.u&&4==(a.g?a.g.readyState:0))gc(a.ca,0,a);else if(V(a,"readystatechange"),4==(a.g?a.g.readyState:0)){a.h=!1;try{var b=uc(a);a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var f;if(f=0===b){var g=String(a.L).match(hc)[1]||null;!g&&A.self&&A.self.location&&(g=A.self.location.protocol.slice(0,-1));f=!jc.test(g?g.toLowerCase():"")}d=
f}d?(V(a,"complete"),V(a,"success")):rc(a)}finally{sc(a)}}}function sc(a,b){if(a.g){pc(a);var c=a.g,d=a.I[0]?function(){}:null;a.g=null;a.I=null;b||V(a,"ready");try{c.onreadystatechange=d}catch(f){}}}function pc(a){a.g&&a.S&&(a.g.ontimeout=null);a.F&&(A.clearTimeout(a.F),a.F=null)}n.isActive=function(){return!!this.g};function uc(a){try{return 2<(a.g?a.g.readyState:0)?a.g.status:-1}catch(b){return-1}};function W(a){S.call(this,a)}w(W,S);n=W.prototype;n.getEnableSsEngine=function(){return O(this,2)};n.getEnableAwr=function(){return O(this,3)};n.getEnableHelpSuggestions=function(){return O(this,4)};n.getAlohaAutoGaRollout=function(){return O(this,5)};n.getEnableConfigurator=function(){return O(this,6)};n.getEnableMweb=function(){return O(this,7)};n.getEnableCtlConsentCheckbox=function(){return O(this,8)};n.getEnableIframe=function(){return O(this,9)};
n.getEnableScreenshotNudge=function(){return O(this,10)};function vc(a){S.call(this,a)}w(vc,S);var wc=["https://sandbox.google.com/tools/feedback"];var xc="af am ar-EG ar-JO ar-MA ar-SA ar-XB ar az be bg bn bs ca cs cy da de-AT de-CH de el en en-GB en-AU en-CA en-IE en-IN en-NZ en-SG en-XA en-XC en-ZA es es-419 es-AR es-BO es-CL es-CO es-CR es-DO es-EC es-GT es-HN es-MX es-NI es-PA es-PE es-PR es-PY es-SV es-US es-UY es-VE et eu fa fi fil fr-CA fr-CH fr gl gsw gu he hi hr hu hy id in is it iw ja ka kk km kn ko ky ln lo lt lv mk ml mn mo mr ms my nb ne nl no pa pl pt pt-BR pt-PT ro ru si sk sl sq sr-Latn sr sv sw ta te th tl tr uk ur uz vi zh zh-CN zh-HK zh-TW zu".split(" ");
function yc(a){var b;return null==(b=a.formContent)?void 0:b.locale};var zc=da(["https://www.gstatic.com/uservoice/feedback/client/web/","/main_binary__",".js"]);function Ac(a){var b=yc(a);b=(b&&xc.includes(b)?yc(a):"en").replaceAll("-","_").toLowerCase();var c;a=(null==(c=a.initializationData)?0:c.useNightlyRelease)?"nightly":"live";return Gb(zc,a,b)};var Bc;function Cc(a,b,c){if(Bc)return Bc;var d=Ac(a);return Bc=b.feedbackV2GlobalObject?Promise.resolve(b.feedbackV2GlobalObject):new Promise(function(f,g){var e=c.createElement("script");e.src=Db(d);Fb(e);e.onload=function(){b.feedbackV2GlobalObject?f(b.feedbackV2GlobalObject):g("feedbackV2GlobalObject not found on window.")};e.onerror=function(){g("Feedback binary script tag failed to load: "+d.toString())};c.body.appendChild(e)})}
function Dc(a,b,c,d,f){f=void 0===f?!0:f;var g,e,h,k,l;return ua(function(m){switch(m.h){case 1:g=Date.now();var q=Cc(a,c,d);m.h=2;return{value:q};case 2:e=m.o;if(!(f||(null==(k=a.initializationData)?0:k.useNightlyRelease)||(null==(l=a.initializationData)?0:l.isLocalServer))){h=e.initializeFeedbackClient(a,g,b);m.h=3;break}q=e.initializeFeedbackClientAsync(a,g,b);m.h=4;return{value:q};case 4:h=m.o;case 3:return h.initiateAloha(),m.return(h)}})}
function Ec(a,b,c){var d=!0;d=void 0===d?!0:d;var f,g,e,h;ua(function(k){g=f=c||A;if(g.isFormOpened)throw e=Error("Form is either loading or already opened"),e.name="DuplicateFormError",e;g.isFormOpened=!0;a.callbacks=a.callbacks||{};h=a.callbacks.onClose||function(){};a.callbacks.onClose=function(l){g.isFormOpened=!1;h(l)};try{return k.return(Dc(a,b,g,f.document,d))}catch(l){throw g.isFormOpened=!1,l;}})};function Fc(a,b){return ua(function(c){return c.return(new Promise(function(d){var f=Gc(null!=b?b:"")+"/aloha_form_properties?productId="+a;mc(f,function(g){var e=g.target;g=null;try{var h=JSON,k=h.stringify;if(e.g){var l=e.g.responseText;0==l.indexOf(")]}'\n")&&(l=l.substring(5));b:{if(A.JSON)try{var m=A.JSON.parse(l);break b}catch(P){}m=$b(l)}}else m=void 0;var q=k.call(h,m);if(null==q||""==q)g=new vc;else{var t=JSON.parse(q);if(!Array.isArray(t))throw Error(void 0);H(t,16);vb=t;var x=new vc(t);
vb=null;g=x}}catch(P){k=new vc,m=new W,m=N(m,5),m=N(m,2),m=N(m,4),m=N(m,8),m=N(m,9),m=N(m,7),m=N(m,10),jb(k),null!=m?nb(m,W):m=void 0,g=M(k,1,m)}d(g)})}))})}function Gc(a){return wc.includes(a)?a:"https://www.google.com/tools/feedback"};function Hc(a,b,c){a.timeOfStartCall=(new Date).getTime();var d=c||A,f=d.document,g=a.nonce||Ib(d);g&&!a.nonce&&(a.nonce=g);if("help"==a.flow){a:{var e=["document","location","href"];for(var h=d||A,k=0;k<e.length;k++)if(h=h[e[k]],null==h){e=null;break a}e=h}!a.helpCenterContext&&e&&(a.helpCenterContext=e.substring(0,1200));e=!0;b&&JSON&&JSON.stringify&&(h=JSON.stringify(b),(e=1200>=h.length)&&(a.psdJson=h));e||(b={invalidPsd:!0})}b=[a,b,c];d.GOOGLE_FEEDBACK_START_ARGUMENTS=b;c=a.feedbackServerUri||
"//www.google.com/tools/feedback";if(e=d.GOOGLE_FEEDBACK_START)e.apply(d,b);else{d=c+"/load.js?";for(var l in a)b=a[l],null==b||ya(b)||(d+=encodeURIComponent(l)+"="+encodeURIComponent(b)+"&");a=(f?new Jb(9==f.nodeType?f:f.ownerDocument||f.document):Ea||(Ea=new Jb)).g;l="SCRIPT";"application/xhtml+xml"===a.contentType&&(l=l.toLowerCase());a=a.createElement(l);g&&a.setAttribute("nonce",g);g=Eb(d);a.src=Db(g);Fb(a);f.body.appendChild(a)}}
function Ic(a,b,c){try{"submit"===a.flow||"help"===a.flow||a.tinyNoPointer?Hc(a,b,c):Fc(a.productId,a.feedbackServerUri).then(function(d){var f=void 0===f?!1:f;var g=tb(d,1,f);var e=!1;var h=null==g||"object"!==typeof g||(e=Array.isArray(g))||g.ba!==hb?e?new W(g):void 0:g;h!==g&&null!=h&&(M(d,1,h,f,!0),H(h.i,I(d.i)&-33));g=h;null!=g&&K(g.i)&&!K(d.i)&&(g=g.O(Da),M(d,1,g,f));d=g;null==d||!d.getAlohaAutoGaRollout()||Ra&&!d.getEnableMweb()?Hc(a,b,c):(f=c||A,g="DEV"===a.serverEnvironment,h=c||A,h=a.nonce||
Ib(h),g={integrationKeys:{productId:a.productId,feedbackBucket:a.bucket},callbacks:{onClose:a.callback,onLoad:a.onLoadCallback},formContent:{locale:a.locale,disableScreenshot:a.disableScreenshotting,productDisplayName:void 0,announcement:void 0,issueCategories:void 0,includeSeveritySelection:void 0,customImageSrc:void 0,thankYouMessage:void 0,la:void 0,defaultFormInputValues:void 0,defaultFormInputValuesString:void 0,abuseLink:a.abuseLink},initializationData:{isLocalServer:g,nonce:h,useNightlyRelease:g,
feedbackJsUrl:void 0,feedbackCssUrl:void 0,feedbackJsUrlSerialized:void 0,feedbackCssUrlSerialized:void 0,submissionServerUri:a.feedbackServerUri,colorScheme:a.colorScheme},extraData:{productVersion:a.productVersion,authUser:a.authuser,configuratorId:a.configuratorId,customZIndex:a.customZIndex,tinyNoPointer:a.tinyNoPointer,allowNonLoggedInFeedback:a.allowNonLoggedInFeedback,enableAnonymousFeedback:a.enableAnonymousFeedback}},b&&(h=new Map(Object.entries(b)),g.extraData.productSpecificData=h),Ec(g,
d,f))},function(d){d&&"DuplicateFormError"!==d.name&&Hc(a,b,c)})}catch(d){Hc(a,b,c)}}var X=["userfeedback","api","startFeedback"],Y=A;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());)X.length||void 0===Ic?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=Ic;}).call(this);
